### ISSUE TITLE
Deprecation of 'past' module

### ISSUE THREAD

**Issue by vermeulendivan** [earthdaily/qgis-plugin#265]
The 'past' module is causing issues as its being deprecated. Have a look at the CMP function.

Here is the error from the Python console:
`Couldn't load plugin 'geosys-plugin' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'past' 
Traceback (most recent call last):
  File "/nix/store/f525xval2icfd1wrchnlpknqnxfxapk2-qgis-ltr-unwrapped-3.28.7/share/qgis/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/Open GIS Stack/python/plugins/geosys-plugin/__init__.py", line 41, in classFactory
    from .geosys.plugin import GeosysPlugin
  File "/nix/store/f525xval2icfd1wrchnlpknqnxfxapk2-qgis-ltr-unwrapped-3.28.7/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/Open GIS Stack/python/plugins/geosys-plugin/geosys/plugin.py", line 39, in 
    from geosys.processing.geosys_processing_provider import (
  File "/nix/store/f525xval2icfd1wrchnlpknqnxfxapk2-qgis-ltr-unwrapped-3.28.7/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/Open GIS Stack/python/plugins/geosys-plugin/geosys/processing/geosys_processing_provider.py", line 26, in 
    from geosys.processing.geosys_processing_algorithm import MapCoverageDownloader
  File "/nix/store/f525xval2icfd1wrchnlpknqnxfxapk2-qgis-ltr-unwrapped-3.28.7/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/Open GIS Stack/python/plugins/geosys-plugin/geosys/processing/geosys_processing_algorithm.py", line 49, in 
    from geosys.ui.widgets.geosys_coverage_downloader import (
  File "/nix/store/f525xval2icfd1wrchnlpknqnxfxapk2-qgis-ltr-unwrapped-3.28.7/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/Open GIS Stack/python/plugins/geosys-plugin/geosys/ui/widgets/geosys_coverage_downloader.py", line 53, in 
    from geosys.utilities.gui_utilities import create_hotspot_layer
  File "/nix/store/f525xval2icfd1wrchnlpknqnxfxapk2-qgis-ltr-unwrapped-3.28.7/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/timlinux/.local/share/QGIS/QGIS3/profiles/Open GIS Stack/python/plugins/geosys-plugin/geosys/utilities/gui_utilities.py", line 4, in 
    from past.builtins import cmp
  File "/nix/store/f525xval2icfd1wrchnlpknqnxfxapk2-qgis-ltr-unwrapped-3.28.7/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'past'

Python version: 3.10.11 (main, Apr  4 2023, 22:10:32) [GCC 12.3.0] 
QGIS version: 3.28.7-Firenze Firenze, exported 

Python Path:
/nix/store/f525xval2icfd1wrchnlpknqnxfxapk2-qgis-ltr-unwrapped-3.28.7/share/qgis/python
/home/timlinux/.local/share/QGIS/QGIS3/profiles/Open GIS Stack/python
/home/timlinux/.local/share/QGIS/QGIS3/profiles/Open GIS Stack/python/plugins
/nix/store/f525xval2icfd1wrchnlpknqnxfxapk2-qgis-ltr-unwrapped-3.28.7/share/qgis/python/plugins
/nix/store/ykgjj0mxrpmi1fbz6avcxglr874nz7s8-python3.10-qscintilla-qt5-2.13.2/lib/python3.10/site-packages
/nix/store/9qn3dbkjkngxi381vswzxvlwiz3ymag3-python3.10-dbus-python-1.2.18/lib/python3.10/site-packages
/nix/store/p1c1i8zprydb2ak73xrf66ibxljjg28r-python3.10-pyqt5-sip-12.11.0/lib/python3.10/site-packages
/nix/store/xn1v165qc9k2z3j90csxbpnrn5hdf0h3-python3.10-PyQt5-5.15.9/lib/python3.10/site-packages
/nix/store/i9fxh7m00b6wz4lbrnb4zk3rlnjp6lwh-gdal-3.6.4/lib/python3.10/site-packages
/nix/store/5313iawqxad75b6m0fwss2hv5qdywpq7-python3.10-Jinja2-3.1.2/lib/python3.10/site-packages
/nix/store/paq83hpci86w236k5g6vikppdqa9i31m-python3.10-babel-2.12.1/lib/python3.10/site-packages
/nix/store/gzryiixdb2bn7amzngdb3rh102xjaikg-python3.10-markupsafe-2.1.2/lib/python3.10/site-packages
/nix/store/b7kiy1c75f7f3lvg05qm913k17f8gdn4-python3.10-numpy-1.24.2/lib/python3.10/site-packages
/nix/store/scccm23n2ng23v3m9r5flsdk75cqmpvv-python3.10-psycopg2-2.9.5/lib/python3.10/site-packages
/nix/store/f8m1hyzvmgv5zby1xid22fyqjppbyl2a-python3.10-chardet-5.1.0/lib/python3.10/site-packages
/nix/store/0wyz82a3mpkz7jsj2qr42kc5lgrm2h9r-python3.10-python-dateutil-2.8.2/lib/python3.10/site-packages
/nix/store/q810mayd6r806ywklhymwwg3fbpzdl01-python3.10-six-1.16.0/lib/python3.10/site-packages
/nix/store/1hi0rxm0ifd5ka74qswh5xa7r6wplwqr-python3.10-pyyaml-6.0/lib/python3.10/site-packages
/nix/store/f6vkic23j890ikjbfdj3z38mzmplfjxy-python3.10-pytz-2023.3/lib/python3.10/site-packages
/nix/store/czahkna42cjl1i4p5dsiawfv4zack0m0-python3.10-requests-2.31.0/lib/python3.10/site-packages
/nix/store/5m05q6fr52vp6kqaay4aqi15ar4i9r05-python3.10-brotlicffi-1.0.9.2/lib/python3.10/site-packages
/nix/store/agbimdar6al0bpjgkdpznnml1bkgq71d-python3.10-cffi-1.15.1/lib/python3.10/site-packages
/nix/store/bp05amgjb89pxxg3558crk0l3s9lcdh4-python3.10-pycparser-2.21/lib/python3.10/site-packages
/nix/store/jni2xb0qyvbvy04vgssdm8cw3m8ymj2l-python3.10-certifi-2022.12.07/lib/python3.10/site-packages
/nix/store/fryixx63nxh7jal0d208ps6akk2l2v65-python3.10-charset-normalizer-3.0.1/lib/python3.10/site-packages
/nix/store/lakbimx4nxr1y6mnjc2jrryx1jr9lx0d-python3.10-idna-3.4/lib/python3.10/site-packages
/nix/store/a800njqgqal9igvlsvyxqwkhhvvigrvv-python3.10-urllib3-1.26.14/lib/python3.10/site-packages
/nix/store/cdwxpydgjjl20iclaqnppic7fv2vv08f-python3.10-brotli-1.0.9/lib/python3.10/site-packages
/nix/store/i4w64m5jsxdk1cl6pbjm3mh7q3inii98-python3.10-pysocks-1.7.1/lib/python3.10/site-packages
/nix/store/gkglqbs6aczi5gfv7mwgllb3q2wrshnr-python3.10-pygments-2.14.0/lib/python3.10/site-packages
/nix/store/fhraysjy7q3jgb549b0w9j3c3sg91hh2-python3.10-docutils-0.19/lib/python3.10/site-packages
/nix/store/9ig1aiy2fvspf25pxfvj2bbs34gfrrar-python3.10-pyqt-builder-1.14.1/lib/python3.10/site-packages
/nix/store/zh48l5jpgg5zpsy5qa76dn01z9yvax41-python3.10-packaging-23.0/lib/python3.10/site-packages
/nix/store/1xd8xix2nc802hdj2gj0k9fjgwpb23hf-python3.10-sip-6.7.7/lib/python3.10/site-packages
/nix/store/riy22zyij2mdnfiyc66lam9a4w5zk8cw-python3.10-ply-3.11/lib/python3.10/site-packages
/nix/store/bi5gqnyby3yr4ks7znm8z7w391jnypxp-python3.10-toml-0.10.2/lib/python3.10/site-packages
/nix/store/bb07jb7p17gm1m733sjc9dv4c2yhnn77-python3.10-setuptools-67.4.0/lib/python3.10/site-packages
/nix/store/m56ffjjybilvixljc0dp9y5x4cwbz7rw-python3.10-owslib-0.29.2/lib/python3.10/site-packages
/nix/store/r457wm71s81dlmasgkx34sn6kzdn6k0m-python3.10-lxml-4.9.2/lib/python3.10/site-packages
/nix/store/2ps9a8z975x7qgz8fghxgzrfaz3fzybc-python3.10-pyproj-3.5.0/lib/python3.10/site-packages
/nix/store/6qk2ybm2yx2dxmx9h4dikr1shjhhbpfr-python3-3.10.11/lib/python310.zip
/nix/store/6qk2ybm2yx2dxmx9h4dikr1shjhhbpfr-python3-3.10.11/lib/python3.10
/nix/store/6qk2ybm2yx2dxmx9h4dikr1shjhhbpfr-python3-3.10.11/lib/python3.10/lib-dynload
/home/timlinux/.local/lib/python3.10/site-packages
/nix/store/6qk2ybm2yx2dxmx9h4dikr1shjhhbpfr-python3-3.10.11/lib/python3.10/site-packages
/home/timlinux/.local/share/QGIS/QGIS3/profiles/Open GIS Stack/python
/home/timlinux/.local/share/QGIS/QGIS3/profiles/Open GIS Stack/python/plugins`

**Comment by mal147** [comment]
won't do
