### ISSUE TITLE
Error when installing the Plugin from Zip

### ISSUE THREAD

**Issue by AndreLester** [earthdaily/qgis-plugin#29]
**Describe the bug**
Error, when loading the plugin from a zip file in QGIS 3.6

**To Reproduce**
1. Download the plugin as zip file from the Github repo
2. In QGIS choose the option, under the Plugins Manger to install from zip.
3. Gives you an error 

**Expected behavior**
The Plugin should install without any warnings.

**Screenshots**
<img width="801" alt="image" src="https://user-images.githubusercontent.com/13916357/55229263-2afcf800-5225-11e9-9b8f-b3a6e2510358.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - QGIS: ver 3.6.0

**Additional context**
Full Error message:

Couldn't load plugin 'geosys-qgis-plugin' due to an error when calling its initGui() method 

ModuleNotFoundError: No module named 'past' 
Traceback (most recent call last):
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 344, in startPlugin
    plugins[packageName].initGui()
  File "/Users/andre/Library/Application Support/QGIS/QGIS3/profiles/testing/python/plugins/geosys-qgis-plugin/geosys/plugin.py", line 165, in initGui
    self._create_dock()
  File "/Users/andre/Library/Application Support/QGIS/QGIS3/profiles/testing/python/plugins/geosys-qgis-plugin/geosys/plugin.py", line 143, in _create_dock
    from geosys.ui.widgets.geosys_dockwidget import (
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/andre/Library/Application Support/QGIS/QGIS3/profiles/testing/python/plugins/geosys-qgis-plugin/geosys/ui/widgets/geosys_dockwidget.py", line 35, in 
    from geosys.utilities.gui_utilities import (
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/andre/Library/Application Support/QGIS/QGIS3/profiles/testing/python/plugins/geosys-qgis-plugin/geosys/utilities/gui_utilities.py", line 3, in 
    from past.builtins import cmp
  File "/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'past'

Python version: 3.6.8 (v3.6.8:3c6b436a57, Dec 24 2018, 02:04:31) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] 
QGIS version: 3.6.0-Noosa Noosa, exported 

Python Path:
/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python
/Users/andre/Library/Application Support/QGIS/QGIS3/profiles/testing/python
/Users/andre/Library/Application Support/QGIS/QGIS3/profiles/testing/python/plugins
/Applications/QGIS3.6.app/Contents/MacOS/../Resources/python/plugins
/Library/Frameworks/SQLite3.framework/Versions/E/Python/3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
/Users/andre/Library/Application Support/QGIS/QGIS3/profiles/testing/python
/Users/andre/Documents/Jobs/geosys/GIS
/Users/andre/Library/Application Support/QGIS/QGIS3/profiles/testing/python/plugins/geosys-qgis-plugin
/Users/andre/Library/Application Support/QGIS/QGIS3/profiles/testing/python/plugins

**Comment by AndreLester** [comment]
I was able to successfully install it on Linux. It probably depends on the underlying Python libraries available. You only need to install the "past" module.
